
export const defaultImage = "/banner.webp"

export const colours = {
    custom_blue_1 : "#00043C",
    custom_blue_2:'#305590',
    custom_blue_3: '#2E579D', 
    custom_blue_4: '#4C7BCB',
    custom_red : "red",
    custom_white_1:"#fffffe",
    custom_white_2 : '#ced4da',
    custom_white_3 : '#f9f9f9',
    custom_maroon :'#800000',
    custom_black : '#000000',
    custom_yellow: '#EEC857',
    custom_grey_1:'#868e96',
    custom_grey_2:"#e8e8fa",
    custom_green_1:'#18A577',
    custom_orange_1:'#ea5803',
    custom_orange_2:'#fbe7d7',
    custom_black_1:'#383733',
    custom_black_2:"#1a1a1a",
}
export const userRole ={
    admin : "admin",
    user : "user"
} as const
export const countries = [
  "Afghanistan",
  "Argentina",
  "Australia",
  "Bangladesh",
  "Brazil",
  "Canada",
  "China",
  "France",
  "Germany",
  "India",
  "Indonesia",
  "Italy",
  "Japan",
  "Mexico",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nigeria",
  "Pakistan",
  "Russia",
  "Saudi Arabia",
  "Singapore",
  "South Africa",
  "South Korea",
  "Sri Lanka",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Vietnam",
];
export const indianStates = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
];